name: Check Backend

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changed python files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            python:
              - 'pyproject.toml'
              - 'invokeai/**'
              - '!invokeai/frontend/web/**'
              - 'tests/**'

      - name: Setup Python
        if: steps.changed-files.outputs.python_any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with pip
        if: steps.changed-files.outputs.python_any_changed == 'true'
        run: |
          pip install ruff

      - name: Ruff check
        if: steps.changed-files.outputs.python_any_changed == 'true'
        run: ruff check --output-format=github .

      - name: Ruff format
        if: steps.changed-files.outputs.python_any_changed == 'true'
        run: ruff format --check .
