name: Check Backend

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with pip
        run: |
          pip install ruff

      - name: Ruff check
        run: ruff check --output-format=github .

      - name: Ruff format
        run: ruff format --check .
